export const ErrorCodes = {
	EXECUTION_NOT_FOUND: 'EXECUTION_NOT_FOUND',
	BLUEPRINT_NOT_FOUND: 'BLUEPRINT_NOT_FOUND',
	NODE_NOT_FOUND: 'NODE_NOT_FOUND',
	EXECUTION_ALREADY_FINISHED: 'EXECUTION_ALREADY_FINISHED',
	NODE_NOT_EXECUTED: 'NODE_NOT_EXECUTED',
	NODE_NOT_FAILED: 'NODE_NOT_FAILED',
	TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
	INVALID_OPERATION: 'INVALID_OPERATION',
} as const
